name: OW2 Status to Discord (hourly)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install requests beautifulsoup4 pillow

      - name: Run status script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          THUMB_URL: https://raw.githubusercontent.com/${{ github.repository }}/main/assets/ow2.png
        run: |
          mkdir -p .bot_state assets
          python scripts/ow_status.py

      - name: Persist state + sparkline
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .bot_state/ow_message_id.txt .bot_state/history.json assets/sparkline.png || true
          git commit -m "update OW status state" || echo "no changes"
          git push || true